version: '3.8'
services:
  postgres_prisma:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=db_prisma
    volumes:
      - prisma_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'  # Puerto expuesto diferente

  postgres_drizzle:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=db_drizzle
    volumes:
      - drizzle_data:/var/lib/postgresql/data
    ports:
      - '5433:5433'  # Otro puerto expuesto

volumes:
  prisma_data:
  drizzle_data:
